@startuml

autonumber

PythonRobot -> CoppeliaSim: simxReadVisionSensor()

activate CoppeliaSim
CoppeliaSim -> PythonRobot: return ballSensorData

alt ballSensorData[0][9] <= 0.3
PythonRobot -> CoppeliaSim: simxSetJointTargetVelocity(rightJoint, 5)
PythonRobot -> CoppeliaSim: simxSetJointTargetVelocity(leftJoint, 5)
else ballSensorData[0][9] > 0.3
PythonRobot -> CoppeliaSim: simxSetJointTargetVelocity(rightJoint, -0.5)
PythonRobot -> CoppeliaSim: simxSetJointTargetVelocity(leftJoint, 0.5)
end

deactivate CoppeliaSim

@enduml